-- MySQL Script generated by MySQL Workbench
-- Fri Apr 19 18:44:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetoBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetoBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoBD` DEFAULT CHARACTER SET utf8 ;
USE `projetoBD` ;

-- -----------------------------------------------------
-- Table `projetoBD`.`Setores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoBD`.`Setores` (
  `IdSetor` INT NOT NULL,
  `nomeSetor` VARCHAR(45) NOT NULL,
  `Criticidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdSetor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoBD`.`Equipamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoBD`.`Equipamentos` (
  `numDeSerie` VARCHAR(50) NOT NULL,
  `TipodeEquipamento` VARCHAR(45) NOT NULL,
  `Fabricante` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Setor_IdSetor` INT NOT NULL,
  PRIMARY KEY (`numDeSerie`, `Setor_IdSetor`),
  INDEX `fk_Equipamento_Setor1_idx` (`Setor_IdSetor` ASC) VISIBLE,
  CONSTRAINT `fk_Equipamento_Setor1`
    FOREIGN KEY (`Setor_IdSetor`)
    REFERENCES `projetoBD`.`Setores` (`IdSetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoBD`.`OrdensdeServiço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoBD`.`OrdensdeServiço` (
  `numOS` INT NOT NULL AUTO_INCREMENT,
  `dataAbertura` VARCHAR(45) NOT NULL,
  `dataFechamento` VARCHAR(45) NOT NULL,
  `descricaoOS` LONGTEXT NOT NULL,
  `SetordeOrigem` VARCHAR(45) NOT NULL,
  `nomedoTecico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoBD`.`OrdensdeServiço_has_Equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoBD`.`OrdensdeServiço_has_Equipamento` (
  `OrdemdeServiço_numOS` INT NOT NULL,
  `Equipamento_numDeSerie` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`OrdemdeServiço_numOS`, `Equipamento_numDeSerie`),
  INDEX `fk_Ordem de Serviço_has_Equipamento_Equipamento1_idx` (`Equipamento_numDeSerie` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_has_Equipamento_Ordem de Serviço1_idx` (`OrdemdeServiço_numOS` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_has_Equipamento_Ordem de Serviço1`
    FOREIGN KEY (`OrdemdeServiço_numOS`)
    REFERENCES `projetoBD`.`OrdensdeServiço` (`numOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_has_Equipamento_Equipamento1`
    FOREIGN KEY (`Equipamento_numDeSerie`)
    REFERENCES `projetoBD`.`Equipamentos` (`numDeSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoBD`.`Tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoBD`.`Tecnicos` (
  `idTecnico` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `Setor_IdSetor` INT NOT NULL,
  PRIMARY KEY (`idTecnico`, `Setor_IdSetor`),
  INDEX `fk_Tecnico_Setor1_idx` (`Setor_IdSetor` ASC) VISIBLE,
  CONSTRAINT `fk_Tecnico_Setor1`
    FOREIGN KEY (`Setor_IdSetor`)
    REFERENCES `projetoBD`.`Setores` (`IdSetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
